version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=your_username
    #   - MONGO_INITDB_ROOT_PASSWORD=your_password
    #   - MONGO_INITDB_DATABASE=your_database_name
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
